service: go-demo

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-2

package:
  patterns:
    - "!./**"
    - "./bin/**"

functions:
  rest:
    handler: bin/rest
    timeout: 2
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: OPTIONS
          cors: true
